version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
    
  db:
    container_name: db
    image: mongo:4.4.0
    volumes:
      - "mongo:/data/db"
    restart: always

  seeder:
    container_name: seeder
    build:
      context: ./seeder

  server:
    container_name: server
    build:
      context: ./server
    links:
      - db
    ports:
      - 80:80
    restart: always

volumes:
  data:
  mongo:
