version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - ./client/src:/usr/src/app/src
      - data:/usr/src/app/public
    
  db:
    container_name: db
    image: mongo:4.4.0
    volumes:
      - "mongo:/data/db"
    restart: always

  seeder:
    container_name: seeder
    build:
      context: ./seeder

  server:
    container_name: server
    depends_on:
      - client
    build:
      context: ./server
    volumes:
       - ./server/src:/usr/src/app/src
       - data:/usr/src/app/public
    links:
      - db
    ports:
      - 80:80
    restart: always

volumes:
  data:
  mongo:
